DROP DATABASE IF EXISTS ej4_tablas;
CREATE DATABASE IF NOT EXISTS ej4_tablas;

USE ej4_tablas;

CREATE TABLE IF NOT EXISTS genre (
idGenre INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
genre VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS album (
idAlbum INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
albumName VARCHAR(255),
dateReleased DATE
);
CREATE TABLE IF NOT EXISTS artist (
idArtist INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
artistName VARCHAR(255)
);