CREATE DATABASE IF NOT EXISTS ej4_Tabla;

USE ej4_Tabla;
CREATE TABLE IF NOT EXISTS Genre (
idGenre INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
genre VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS Album (
idAlbum INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
albumName VARCHAR(255),
dateReleased DATE
);
CREATE TABLE IF NOT EXISTS Artist (
idArtist INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
artistName VARCHAR(255)
);