USE db_autogenerated;
SELECT * FROM mytable;
/* 1 */ 
SELECT postalZip AS Código_Postal,region AS Región,country AS País FROM mytable;
/* 2 */
SELECT * FROM mytable WHERE phone LIKE "(811)%";
/* 3 */
SELECT * FROM mytable WHERE country = "Italy" OR country = "Spain";
/* 4 */
SELECT COUNT(id) FROM mytable;
/* 5 */
SELECT region,country,postalZip FROM mytable WHERE id IN (SELECT id FROM mytable WHERE country = "Germany" OR country ="Turkey");
/* 6 */
SELECT MIN(id),MAX(id) FROM mytable;
/* 7 */
SELECT country,COUNT(country) FROM mytable GROUP BY country;
/* 8 */
SELECT * FROM mytable ORDER BY postalZip LIMIT 10;
/* 9 */
DELETE FROM mytable WHERE country = "Singapore";

